### ISSUE TITLE
GUI for Static representation of Compute Graph

### ISSUE THREAD

**Issue by CanBayraktaroglu** [CanBayraktaroglu/C-ML#6]

**Comment by kingbaldwin-iv** [comment]
psuhladim. Makefile olarak bunu kullanabilirsin, sonra "make run":
```
# Name of the output executable
TARGET = visualizer

# Compiler
CC = gcc

# Source files
SRC = visualizer.c

# Compiler flags
CFLAGS = -framework OpenGL -framework Cocoa -framework IOKit -framework CoreVideo -L/opt/homebrew/lib -lraylib

# Build target
$(TARGET): $(SRC)
	$(CC) $(SRC) -o $(TARGET) $(CFLAGS)

# Run the executable
run: $(TARGET)
	./$(TARGET)

# Clean up build files
clean:
	rm -f $(TARGET)

# Default target when running `make`
default: $(TARGET) run
```

**Comment by CanBayraktaroglu** [comment]
@kingbaldwin-iv compilerin generate ettigi makefile i nasil ignorelaticam problem olmadan? kaldirip bu Makefilei ekleyip make runladigimda "make: *** No rule to make target 'visualizer.c', needed by 'visualizer'.  Stop." errorini aliyorum

**Comment by CanBayraktaroglu** [comment]
bi de ozanim robustness > memory complexity bence prioritise etmemiz gereken. genel olarak counterlar ve num_..  variablelar icin integer64 yerine size_t (unsigned long int) kullanmaya dikkat et lutfen.

**Comment by CanBayraktaroglu** [comment]
ayni haseple float yerine double

**Comment by CanBayraktaroglu** [comment]
hayalimizdeki gibi bi noktada asiri large scale modelleri implemente ettigimiz zaman retrospective róbustness turlariyla ugrasmayak

**Comment by kingbaldwin-iv** [comment]
> ayni haseple float yerine double

floatlar sadece raylib API icin. direk float double implicit casting oldugu icin zaten gerekli herhangi bir noktada sorun cikaracagini sanmam (cpuler etc. zaten genelde float verildiginde otomatik implicit conversion yapip aritmetige ordan devam ediyorlar). size_t degisikiligi aklimda, duzeltirim.

**Comment by kingbaldwin-iv** [comment]
> @kingbaldwin-iv compilerin generate ettigi makefile i nasil ignorelaticam problem olmadan? kaldirip bu Makefilei ekleyip make runladigimda "make: *** No rule to make target 'visualizer.c', needed by 'visualizer'. Stop." errorini aliyorum

orijinal makefile a direk flagleri ekliyebiliriz ekstra bir command uzerinden (e.g "make run" default flagleri kullanir, "make visualize" ekstradan -framework OpenGL -framework Cocoa -framework IOKit -framework CoreVideo -L/opt/homebrew/lib -lraylib flaglerini kullanir) boylelikle binaryler gerksiz buyuk olmaz visualisation istemedigimizde

**Comment by CanBayraktaroglu** [comment]
bunu halledebilir misin ozan bu issue icinde? standardize bir build surecine ihtiyac var her turlu.

**Comment by kingbaldwin-iv** [comment]
> > @kingbaldwin-iv compilerin generate ettigi makefile i nasil ignorelaticam problem olmadan? kaldirip bu Makefilei ekleyip make runladigimda "make: *** No rule to make target 'visualizer.c', needed by 'visualizer'. Stop." errorini aliyorum
> 
> orijinal makefile a direk flagleri ekliyebiliriz ekstra bir command uzerinden (e.g "make run" default flagleri kullanir, "make visualize" ekstradan -framework OpenGL -framework Cocoa -framework IOKit -framework CoreVideo -L/opt/homebrew/lib -lraylib flaglerini kullanir) boylelikle binaryler gerksiz buyuk olmaz visualisation istemedigimizde

burda tabi local bilgisayarin raylib i download etmis olmasi onemli de onu kullanici compiler errorunden anlar diye dusunuyorum

**Comment by kingbaldwin-iv** [comment]
> bunu halledebilir misin ozan bu issue icinde? standardize bir build surecine ihtiyac var her turlu.

yarin halletmeye calisicam

**Comment by CanBayraktaroglu** [comment]
bir adet requirements.txt tarzinda external dependency listelenmesine ihtiyacimiz var haklisin

**Comment by CanBayraktaroglu** [comment]
ya ReadMede acik ve uyarici sekilde veya requirements.txt tadinda

**Comment by kingbaldwin-iv** [comment]
direk makefile otomatik raylibi download eden script yukleyebilirim

**Comment by CanBayraktaroglu** [comment]
diger issueda feed forward layeri yazdim autodiffe gore bu arada, sequential modeli modify etmem gerekli; bu sirada gordugum porblemleri optimize ediyorum bi de. haber vericem makul bi pipe haline gelebildiginde

**Comment by CanBayraktaroglu** [comment]
> direk makefile otomatik raylibi download eden script yukleyebilirim

bunu ya böyle halledicez ya da dockerfile in icinde bunlari indirecek commandi ekleyecegiz gelecekte.

**Comment by kingbaldwin-iv** [comment]
> diger issueda feed forward layeri yazdim autodiffe gore bu arada, sequential modeli modify etmem gerekli; bu sirada gordugum porblemleri optimize ediyorum bi de. haber vericem makul bi pipe haline gelebildiginde

bir de dfs belki topological sortda bfsle degisebilir, eger cok fazla node olursa optimize performans icin stack buyuklugu baya azalir

**Comment by CanBayraktaroglu** [comment]
> > diger issueda feed forward layeri yazdim autodiffe gore bu arada, sequential modeli modify etmem gerekli; bu sirada gordugum porblemleri optimize ediyorum bi de. haber vericem makul bi pipe haline gelebildiginde
> 
> bir de dfs belki topological sortda bfsle degisebilir, eger cok fazla node olursa optimize performans icin stack buyuklugu baya azalir

"visited" variablei sayesinde hallolmustur diye dusunuyodum ama haklisin. bfs daha mantikli unique traversal adina

**Comment by CanBayraktaroglu** [comment]
halledic3m

**Comment by kingbaldwin-iv** [comment]
bir de ComputeGraph daki ADNodes** nodes tahminen layer basina nodelari bulunduruyor diye dusunuyorum. ekstradan size_t[n_layers][n] tarzi bir field her layerda kac node oldunu gosterebilirse is baya kolaylasir cunku parametre olarak geldigi icin sizeof(array) / sizeof(array[0]) bana layer basina nodelari vermiyor ve sifirdan graphi build etmem gerekiyor

**Comment by kingbaldwin-iv** [comment]
> > > diger issueda feed forward layeri yazdim autodiffe gore bu arada, sequential modeli modify etmem gerekli; bu sirada gordugum porblemleri optimize ediyorum bi de. haber vericem makul bi pipe haline gelebildiginde
> > 
> > 
> > bir de dfs belki topological sortda bfsle degisebilir, eger cok fazla node olursa optimize performans icin stack buyuklugu baya azalir
> 
> "visited" variablei sayesinde hallolmustur diye dusunuyodum ama haklisin. bfs daha mantikli unique traversal adina

visited fieldindan da kurtulmus oluruz bfsle yaparsak
